export default {
	currentSong: {
		playback: {},
		soundObj: {},
		detail: {
			id: 12,
			title: 'Stay x Ranjha x Dr Gode • Bpraak • Justin Bieber',
			author: 'Bpraak • Justin Bieber • Jasleen Royal',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-6.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Stay-x-Ranjha-x-Dr-Gode-•-Bpraak-•-Justin-Bieber.mp3',
			durationMillis: 183000,
		},
		playbackStatus: {},
	},
	songs: [
		{
			id: 1,
			title: 'Voices',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Voices-OFFICIAL-VIDEO.mp3',
			durationMillis: 207000,
		},
		{
			id: 2,
			title: 'Almost Forgot About You',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-1.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Almost-Forgot-OFFICIAL-VIDEO.mp3',
			durationMillis: 209000,
		},
		{
			id: 3,
			title: 'Heart Attack - Demi Lovato',
			author: 'Against The Current & Sam Tsui',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/artworks-000131397077-p687lz-t500x500.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Heart-Attack-Demi-Lovato-Sam-Tsui-_-Chrissy-Costanza-of-ATC.mp3',
			durationMillis: 234000,
		},
		{
			id: 4,
			title: 'Gravity',
			author: 'Against The Current',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/2e6c0cd268c3f89447e33a91ac39fe44.1000x1000x1.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Against-The-Current-Gravity-Official-Music-Video.mp3',
			durationMillis: 233000,
		},
		{
			id: 5,
			title: 'Face off x Scary garry',
			author: 'Y_X Mashup',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-2.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Face-off-x-Scary-garry-Full-Version-Y_X-Mashup.mp3',
			durationMillis: 233000,
		},
		{
			id: 6,
			title: 'Alone - Fortnite Mix',
			author: 'Marshmello',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/400x400cc.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marshmello-Alone-Fortnite-Music-Video.mp3',
			durationMillis: 203000,
		},
		{
			id: 7,
			title: 'Numb - GMV',
			author: 'Linkin Park',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/artworks-000105604285-me2956-t500x500.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Numb-Linkin-Park-GMV.mp3',
			durationMillis: 209000,
		},
		{
			id: 8,
			title: 'BIBA feat. Shirley Setia & Shah Rukh Khan',
			author: 'Marshmello x Pritam',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-3.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marshmello-x-Pritam-BIBA-feat.-Shirley-Setia-Shah-Rukh-Khan-Official-Music-Video.mp3',
			durationMillis: 218000,
		},
		{
			id: 9,
			title: ' Genda Phool',
			author: 'Badshah',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/Genda2BPhool2BSong2BImage2BBy2BBadshah.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Badshah-–-Genda-Phool-_-Jacqueline-Fernandez-_-Payal-Dev-_-Hit-Anthem-of-the-Year-2021.mp3',
			durationMillis: 174000,
		},
		{
			id: 10,
			title: 'Gangstas Paradise',
			author: 'Coolio',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/Gangstas_paradise.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Gangstas-Paradise.mp3',
			durationMillis: 241000,
		},
		{
			id: 11,
			title: 'Marvel Anthem',
			author: 'A.R. Rahman',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-4.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Marvel-Anthem-_-A.R.-Rahman-_-Hindi.mp3',
			durationMillis: 166000,
		},
		{
			id: 12,
			title: 'Stay x Ranjha x Dr Gode • Bpraak • Justin Bieber',
			author: 'Bpraak • Justin Bieber • Jasleen Royal',
			img: 'https://shotoe.tech/wp-content/uploads/2021/12/maxresdefault-6.jpg',
			uri: 'https://shotoe.tech/wp-content/uploads/2021/12/Stay-x-Ranjha-x-Dr-Gode-•-Bpraak-•-Justin-Bieber.mp3',
			durationMillis: 183000,
		},
	],
};
